name: "Run tests"
on: 
  pull_request:
    branches: ['master', 'develop']

jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11.0.11'

    - uses: gradle/gradle-build-action@v2

    - uses: android-actions/setup-android@v2

    - name: "Create debug.properties file"
      run: "echo 'KEY_STORE_FILE_PATH = path\nKEY_STORE_PASSWORD = password\nKEY_ALIAS = alias\nKEY_ALIAS_PASSWORD = password\nTASK_CONFIGURATOR_ENVIRONMENT = \"development\"\nOPERATION_LOGGING_ENABLED = \"true\"\nJOKES_ENDPOINT = \"endpoint\"' > debug.properties"
      working-directory: Jokes/app

    - name: "Create development.properties file"
      run: "echo 'KEY_STORE_FILE_PATH = path\nKEY_STORE_PASSWORD = password\nKEY_ALIAS = alias\nKEY_ALIAS_PASSWORD = password\nTASK_CONFIGURATOR_ENVIRONMENT = \"development\"\nOPERATION_LOGGING_ENABLED = \"true\"\nJOKES_ENDPOINT = \"endpoint\"' > development.properties"
      working-directory: Jokes/app

    - name: "Create production.properties file"
      run: "echo 'KEY_STORE_FILE_PATH = path\nKEY_STORE_PASSWORD = password\nKEY_ALIAS = alias\nKEY_ALIAS_PASSWORD = password\nTASK_CONFIGURATOR_ENVIRONMENT = \"production\"\nOPERATION_LOGGING_ENABLED = \"false\"\nJOKES_ENDPOINT = \"endpoint\"' > production.properties"
      working-directory: Jokes/app

    - name: "Run tests"
      run: "./gradlew app:testDebugUnitTest"
      working-directory: Jokes